### ISSUE TITLE
Abuja photos

### ISSUE THREAD

**Issue by Hafuka101** [Ruinscraft/mcatlas-history#1]
![Abuja (1) with legend](https://user-images.githubusercontent.com/67900941/105632624-6fbf3d80-5e54-11eb-88c8-7cd3778297e6.jpg)

![Abuja (3)](https://user-images.githubusercontent.com/67900941/105632627-76e64b80-5e54-11eb-8ead-ec31e329137c.png)

![Abuja (2)](https://user-images.githubusercontent.com/67900941/105632727-10156200-5e55-11eb-8a0c-b7a86df1d06e.png)

![2021-01-24_17 38 25](https://user-images.githubusercontent.com/67900941/105637124-119e5480-5e6c-11eb-9f53-634b9037c137.png)

![Abuja panorama (1)](https://user-images.githubusercontent.com/67900941/105641604-30f5ab80-5e85-11eb-8963-9fbc00814a44.png)
![Abuja panorama (2)](https://user-images.githubusercontent.com/67900941/105641607-32bf6f00-5e85-11eb-8539-cb613446ad12.png)
![Abuja panorama (3)](https://user-images.githubusercontent.com/67900941/105641608-3521c900-5e85-11eb-9a11-1bc4fdb421e8.png)
![Abuja panorama (4)](https://user-images.githubusercontent.com/67900941/105641611-394de680-5e85-11eb-8549-3abc520a8e87.png)

**Comment by drewdorris** [comment]
Not the appropriate place to put these, you can add them to the page here https://github.com/Ruinscraft/mcatlas-history/wiki/Abuja
